version: '2'

services:
    es:
        build: elasticsearch/
        ports:
            - 9200:9200
        networks:
            - backend
        volumes:
            - es_data:/usr/share/elasticsearch/data

    logstash:
        build: logstash/
        ports:
            - 5044:5044
        networks:
            - backend

    kibana:
        image: kibana
        environment:
            ELASTICSEARCH_URL: http://es:9200
        depends_on:
            - es
        ports:
            - 5601:5601
        networks:
            - backend

volumes:
    es_data:

networks:
    backend:
                            
